distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.16.2
install_time: "Thu May 25 19:34:25 2023"
installation_id: "4f882017-46fa-4b63-94e8-1e731e7a634e"
rime_version: 1.8.5